ACCESS_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTU4ODQ4NzUsImlhdCI6MTcxNTcxMjA3NSwiaXNzIjoidGd0Z19zb3RlcmlhIiwidCI6IkJpcjIxeFZqU3hTclcwUEpBTC02OXc6MDoxIiwic3ViIjoiMzUzNDI3NiJ9.LVer7aXTfZmN701RTl7tdyyT4tW821pdixhic6ymIMQ',
REFRESH_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDcyNDgwNzUsImlhdCI6MTcxNTcxMjA3NSwiaXNzIjoidGd0Z19zb3RlcmlhIiwidCI6IkxwZWFsckhFUmVPbmhBaU1kRnlqZWc6MDowIiwic3ViIjoiMzUzNDI3NiJ9.BtcQ5je0DytPcUPaE9hO8uocgTUIyqYfh2ej1u_HYpM',
TGTG_USER_ID: '3534276',
COOKIE: 'datadome=e_pWyT6E4iSTAzotxRGBR0G9~0oBodrAmV0tcoY~w_la3uBIk9MnDBDjg6CVGxdJ75HXlGAxTsdz0sfFnIiLA9GUUd5GH9Ik8k6dm2VebZzdppQYzzJdnEher9WQpLt5; Max-Age=5184000; Domain=.apptoogoodtogo.com; Path=/; Secure; SameSite=Lax',
TG_BOT_ID: '7135531971'
TG_CHAT_ID: '7038358942'
